name: test

on:
  - push
  - pull_request

jobs:
  execute:
    name: execute
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: ./download-gh.sh
      - run: test -f ./gh.tar.gz
      - run: ./download-gh.sh /tmp
      - run: test -f /tmp/gh.tar.gz
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://koalaman/shellcheck:stable
        with:
          args: ./download-gh.sh
